### PR TITLE
Use name instead of parent_group for Manipulator name (#29)

### PR DESCRIPTION
**Pull request by dmcconachie**
We should verify that our URDF and SRDF still works with these changes, then merge this in to our fork.
https://github.com/personalrobotics/or_urdf/pull/29

### CODE REVIEW

**Comment by bsaund** [comment]
This changes the names of the openrave manipulators.
right_arm -> right_ee

This is currently in conflict with `openrave_planner.set_manipulator` and the corresponding or_controller. 


1) Do we have repos (other than victor_or_controllers) where this is a dependency? (Will this change break other stuff?)
2) `set_manipulator("right_arm")` and `set_manipulator("right_ee")` are approximately equivalently easy to read.
3) Probably worth it to change soon so we stay up to date with personal robotics? 
4) If we do change, let's wait until my current changes for dual arm stuff have been reviewed and merged.

**Comment by dmcconachie** [comment]
Works for me.

**Comment by dmcconachie** [comment]
@bsaund Are the dual arm changes at a point where merging this makes sense?

**Comment by bsaund** [comment]
Go ahead and merge

**Pull request merged**
